# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkingTestingTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkingTestingTutorial
  pod 'Moya', '~> 14.0'
  pod 'Alamofire', '~> 5.4'

end
